export const FETCH_POSTS_START = "FETCH_POSTS_START";
export const FETCH_POSTS_COMPLETED = "FETCH_POSTS_COMPLETED";
export const FETCH_POSTS_ERROR = "FETCH_POSTS_ERROR";
export const ADD_POST = "ADD_POST";
export const REMOVE_POST = "REMOVE_POST";